### PR TITLE
ref: added deployed contracts' addresses, testing on Polygonscan

### PR DESCRIPTION
**Pull request by accompany1205**
deployed updated contracts
MockUSDT: 0x17896eD288A0aE8a604b859bc3FdB4f3f9102e0a
StreamManager: 0xd34541599Eb965a5EF715725f48b285DA9E34d6F

### CODE REVIEW

**Comment by accompany1205** [comment]
@markholdex , @zolotokrylin I'm having tests for updated StreamManager on Polygonscan.

**Comment by markholdex** [comment]
@accompany1205 contracts are not verified on the explorer and I don't see any activity in them. We agreed that you will test and let u know the results yesterday. What are the results of testing?

**Comment by accompany1205** [comment]
@markholdex The contracts were verified already yesterday.
However, I coudln't test the updates of StreamManager since my network connect was not good yesterday.
I will do them now asap.

**Review by markholdex — APPROVED** [review]

**Review by markholdex — CHANGES_REQUESTED** [review]
Please, resolve existing comment. Thx

**Comment by markholdex** [comment]
@accompany1205 please provide the new addresses that you deployed to Sepolia. Thanks!

**Pull request merged**
