### PR TITLE
Test: Increased smart-contracts test coverage upto 100%

### LINKED ISSUE #78: Problem: smart-contracts test coverage is not 100%
Latest reports show that Branch test coverage is only 91%. For the safest and best result, the coverage should be 100%

### PR DESCRIPTION
**Pull request by accompany1205**
resolves #78

### CODE REVIEW

**Comment by georgeciubotaru** [comment]
@accompany1205 What is the ETA here?

Let's try one method.
1 PR with full coverage for 1 function.

**Comment by accompany1205** [comment]
@georgeciubotaru What is the ETA for?

**Comment by georgeciubotaru** [comment]
@accompany1205 Estimation for finishing this task?

**Comment by accompany1205** [comment]
@georgeciubotaru by today

**Comment by accompany1205** [comment]
--------------------|----------|----------|----------|----------|----------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------|----------|----------|----------|----------|----------------|
 contracts\         |      100 |    95.59 |      100 |      100 |                |
  MockUSDT.sol      |      100 |      100 |      100 |      100 |                |
  StreamManager.sol |      100 |    95.59 |      100 |      100 |                |
--------------------|----------|----------|----------|----------|----------------|
All files           |      100 |    95.59 |      100 |      100 |                |
--------------------|----------|----------|----------|----------|----------------|

@georgeciubotaru Can you help me raise the %Branch upto 100%?

**Comment by georgeciubotaru** [comment]
@accompany1205 The coverage `folder` is your Bible here, just use it and it will help you to find the missing test cases.
`coverage/index.html`

**Comment by accompany1205** [comment]
@georgeciubotaru Could you help me in detail?
I can only find 65/68. I need specific lines.
I think all the cases are implemented in the contract, but not sure in imported modules.

**Comment by georgeciubotaru** [comment]
@accompany1205 Have you opened the `coverage.html` file?

All you need is in the file:
image

**Comment by accompany1205** [comment]
@georgeciubotaru Could you let me know where can I find coverage.html

**Comment by georgeciubotaru** [comment]
@accompany1205 I don't think it's a good idea to remove that `nonReentrant` modifier. Try to cover it too

**Comment by georgeciubotaru** [comment]
@accompany1205 How about defining a mock contract with the method

Current contract - A
Mock Contract B


A.claim() => B.transfer()

B.transfer() {
    A.claim();
   ///  balances changes
}

**Comment by accompany1205** [comment]
@georgeciubotaru I already tried like that, but contract B's address is not a payee so isPayee() returns false. Impossible to claim.

**Comment by georgeciubotaru** [comment]
@accompany1205 How about transforming contract B into a payee?

**Comment by accompany1205** [comment]
@georgeciubotaru impossible
In this case, it can't call claim function because no signer or provider there.

**Comment by georgeciubotaru** [comment]
@accompany1205 How about to change the places for modifiers put `nonReentrant` as the first one

**Comment by accompany1205** [comment]
Wow, wonderful. It works

**Comment by accompany1205** [comment]
@georgeciubotaru Could you review it?

**Review by georgeciubotaru — APPROVED** [review]

**Comment by accompany1205** [comment]
@georgeciubotaru Perfect.
I learned it from you. TBH, Kevin also tought me how to do that, but I didn't.
Hope I learn much from you.

**Pull request merged**
